# Generated by Django 5.2.8 on 2026-01-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
