# Generated by Django 5.2.8 on 2026-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_alter_user_role_academicsupervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'internship')},
        ),
    ]
