# Generated by Django 5.2.8 on 2026-01-14 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_alter_user_role_academicsupervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicsupervisor',
            old_name='department',
            new_name='faculty',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'internship')},
        ),
    ]
