# Generated by Django 5.2.8 on 2026-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_internshipapplication_decision_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
