# Generated by Django 5.2.8 on 2026-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_logbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='company_supervisor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='company_question_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='academic_supervisor_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='company_supervisor_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
