# Generated by Django 5.2.8 on 2026-01-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_logbook_company_supervisor_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.academicsupervisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
        ),
    ]
